# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 晦鸣
author: Robert Zhang
email: louirobert@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  风雨如晦，鸡鸣不已，既见君子，云胡不喜
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://example.com" # the base hostname & protocol for your site
github_username:  coin8086
weibo_username: acadamus
zhihu_username: robert-zh

# Build settings
markdown: kramdown
theme: minima
google_analytics: "UA-85747376-1"

paginate: 10

tag_page_layout: tag_page
tag_page_dir: tags
# It's too bad to have to put the followings in config: it should be put in
# Front Matter but unfortunately jekyll-tagging doesn't read YAML in
# tag_page_layout file.
tag_page_data:
  script: tag_cloud_js.html

defaults:
  - scope:
      path: _posts/programming-challenges
      type: posts
    values:
      layout: programming-challenges
      excerpt_separator: <!--more-->
      tags: algorithm 挑战编程
      categories: programming-challenges
      permalink: /:categories/:title.html
